CREATE TABLE `productos` (
  `id_cartera` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `nombre` VARCHAR(255),
  `descripcion` VARCHAR(255),
  `categoria` VARCHAR(255),
  `precio_base` VARCHAR(255),
  `unidad_medida` VARCHAR(255)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L520', 'LICUADORA STROBER ESCOLTA 36 LEDS VASO AMARILLO DUAL-VOLT', 'LICUADORA', '76533', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L540', 'LICUADORA CUADRADA BAJO PERFIL NEON LUX DUAL VOLT', 'LICUADORA', '305882', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L550', 'LICUADORA CUADRADA 6 MODULOS 84W DUAL VOLT', 'LICUADORA', '223529', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L570', 'LICUADORA DOBLE STROBER DUAL-VOLT', 'LICUADORA', '176471', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L580', 'LICUADORA CUADRADA 4 MODULOS DUAL-VOLT', 'LICUADORA', '270588', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L101', 'LAMPARA LATERAL 6 LED DUAL VOLT 2CTS', 'LATERALES', '9405', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L102', 'LAMPARA LATERAL 7 LED DUAL VOLT 2CTS', 'LATERALES', '11400', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L103', 'LAMPARA LATERAL 8 LED DUAL VOLT 2CTS', 'LATERALES', '11935', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L104', 'LAMPARA LATERAL 16 LED AMERICAN DUAL VOLT', 'LATERALES', '16751', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L106', 'LAMPARA LATERAL 12 LEDS APOLO DUAL-VOLT', 'LATERALES', '20278', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L108', 'LAMPARA LATERAL 24 LEDS SIN ARO DUAL VOLT', 'LATERALES', '29975', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L108P', 'LAMPARA LATERAL 24 LEDS ARO PLASTICO DUAL VOLT', 'LATERALES', '33502', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L108A', 'LAMPARA LATERAL 24 LEDS ARO ACERO DUAL VOLT', 'LATERALES', '43152', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L108SP', 'LAMPARA LATERAL 24 LEDS ARO PLASTICO SOBREPONER DUAL VOLT', 'LATERALES', '33502', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L109', 'LAMPARA DIRECCIONAL FLECHA 25 LEDS SIN ARO DUAL VOLT', 'LATERALES', '38169', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L109A', 'LAMPARA DIRECCIONAL FLECHA 25 LEDS ARO ACERO DUAL VOLT', 'LATERALES', '51087', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L109P', 'LAMPARA DIRECCIONAL FLECHA 25 LEDS ARO PLASTICO DUAL VOLT', 'LATERALES', '41436', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L109SP', 'LAMPARA DIRECCIONAL FLECHA 25 LEDS ARO PLASTICO SOBREPONER DUAL VOLT', 'LATERALES', '41436', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L110', 'LAMPARA LATERAL PLANA 12 LEDS ARO PLASTICO DUAL-VOLT', 'LATERALES', '20635', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L111A', 'LAMPARA LATERAL OVALADA NEON LUX ARO ACERO DUAL-VOLT', 'LATERALES', '48442', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L111', 'LAMPARA LATERAL OVALADA NEON LUX SIN ARO DUAL-VOLT', 'LATERALES', '35266', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L111P', 'LAMPARA LATERAL OVALADA NEON LUX ARO PLASTICO DUAL-VOLT', 'LATERALES', '38792', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L111SP', 'LAMPARA LATERAL OVALADA NEON LUX ARO PLASTICO SOBREPONER DUAL-VOLT', 'LATERALES', '38792', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L112', 'LAMPARA LATERAL RECTANGULAR NEON LUX DUAL VOLT', 'LATERALES', '28212', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L113', 'LAMPARA LATERAL PERLADA 12 LED SMD DUAL VOLT', 'LATERALES', '15869', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L114', 'LAMPARA LATERAL COMBINADO SMD DUAL VOLT', 'LATERALES', '15869', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L115', 'LAMPARA LATERAL 18 LED SMD DUAL VOLT', 'LATERALES', '21159', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L116', 'LAMPARA LATERAL OVALADO BARRIGA NEON-LUX SIN ARO DUAL-VOLT', 'LATERALES', '39163', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L116A', 'LAMPARA LATERAL OVALADO BARRIGA NEON-LUX ARO ACERO DUAL-VOLT', 'LATERALES', '49998', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L116P', 'LAMPARA LATERAL OVALADO BARRIGA NEON-LUX ARO PLSTICO DUAL-VOLT', 'LATERALES', '42411', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L116SP', 'LAMPARA LATERAL OVALADO BARRIGA NEON-LUX ARO SOBREPONER DUAL-VOLT', 'LATERALES', '42411', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L117', 'LAMPARA LATERAL ROMARCO ESMERALDA SIN ARO DUAL-VOLT', 'LATERALES', '44163', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L117A', 'LAMPARA LATERAL ROMARCO ESMERALDA ARO ACERO DUAL-VOLT', 'LATERALES', '54998', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L117P', 'LAMPARA LATERAL ROMARCO ESMERALDA ARO PLASTICO DUAL-VOLT', 'LATERALES', '47411', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L117SP', 'LAMPARA LATERAL ROMARCO ESMERALDA ARO SOBREPONER DUAL-VOLT', 'LATERALES', '47411', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L123', 'LAMPARA LATERAL RECTANGULAR PEQUEÑA NEON LUX', 'LATERALES', '15869', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L125', 'LAMPARA LATERAL RECTANGULAR MEDIANA NEON LUX DUAL VOLT', 'LATERALES', '24686', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('L126', 'LAMPARA LATERAL MORRISON NEON CON ARO MARCADO DUAL-VOLT', 'LATERALES', '20912', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S302', 'SEM DOBLE CARA CUADRADO 56 LEDS DUAL VOLT', 'SEMAFOROS', '92572', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S303', 'SEM DOBLE REGLETA 18 LED PERNO', 'SEMAFOROS', '42319', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S304', 'SEM DOBLE REGLETA 36 LED PERNO PQ X 2', 'SEMAFOROS', '134115', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S305', 'SEMAFORO TRIPLE REGLETA 39 LED SOBREPONER X 2', 'SEMAFOROS', '141174', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S306', 'SEM DOBLE CARA CUADRADO NEON LUX', 'SEMAFOROS', '96980', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S307', 'SEMAFORO REGLETA 17CM PERNO NEON LUX', 'SEMAFOROS', '45845', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S308', 'SEMAFORO REGLETA 31CM PERNO NEON LUX x 2', 'SEMAFOROS', '148233', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S310', 'SEMAFORO REGLETA TRIPLE 23CM SOBREPONER NEON-LUX X 2', 'SEMAFOROS', '155292', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S311', 'SEM REGLETA TRIPLE 17CM DE SOBREPONER NEON LUX', 'SEMAFOROS', '59951', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S312', 'SEM REGLETA TRIPLE DE SOBREPONER 23 LED FLUXS', 'SEMAFOROS', '55542', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S313', 'SEMAFORO REGLETA DOBLE 10 LED FLUXS', 'SEMAFOROS', '34384', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S314', 'SEMAFORO REGLETA DOBLE 10 CM NEON LUX', 'SEMAFOROS', '36147', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S315', 'SEMAFORO CUADRADO 3" AUXILIAR PERLADO', 'SEMAFOROS', '46374', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S326', 'SEMAFORO CUADRADO 3" AUXILIAR NEON LUX', 'SEMAFOROS', '55191', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S316', 'SEMAFORO PEPINO SENCILLO BAJO DUAL VOLT PQ X 2', 'SEMAFOROS', '152468', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S317', 'SEMAFORO PEPINO DOBLE BAJO DUAL VOLT', 'SEMAFOROS', '137086', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S318', 'SEMAFORO PEPINO SENCILLO ALTO DUAL VOLT', 'SEMAFOROS', '76234', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S319', 'SEMAFORO PEPINO DOBLE ALTO DUAL VOLT', 'SEMAFOROS', '137086', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S309', 'STOP TRIPLE SOBREPONER CUADRADO CON REGLETA 86 LEDS DUAL VOLT', 'STOPS', '131400', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S404', 'STOP 4" NEON-LUX SIN ARO DUAL-VOLT', 'STOPS', '35266', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S404A', 'STOP 4" NEON-LUX ARO ACERO DUAL-VOLT', 'STOPS', '45854', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S404P', 'STOP 4" NEON-LUX ARO PLASTICO DUAL VOLT', 'STOPS', '38792', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S404SP', 'STOP 4" NEON-LUX ARO PLASTICO SOBREPONER DUAL VOLT', 'STOPS', '38792', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S405', 'STOP 4" PERLADO TIPO IMPORTADO SIN ARO DUAL-VOLT', 'STOPS', '29975', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S405A', 'STOP 4" PERLADO TIPO IMPORTADO ARO ACERO DUAL-VOLT', 'STOPS', '40565', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S405P', 'STOP 4" PERLADO TIPO IMPORTADO ARO PLASTICO DUAL-VOLT', 'STOPS', '33502', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S405SP', 'STOP 4" PERLADO TIPO IMPORTADO ARO PLASTICO SOBREPONER DUAL-VOLT', 'STOPS', '33502', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S407', 'STOP TRIPLE SOBREPONER CUADRADO NEON LUX DUAL VOLT', 'STOPS', '137534', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S408', 'STOP TRIPLE PEQUEÑO PERLADO SENCILLO DUAL-VOLT', 'STOPS', '55547', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S409', 'STOP TRIPLE PEQUEÑO PERLADO CON REGLETA DUAL-VOLT', 'STOPS', '77584', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S410', 'STOP 2" PERLADO SIN ARO', 'STOPS', '13048', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S410A', 'STOP 2" PERLADO ARO ACERO', 'STOPS', '18931', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S411', 'STOP 2"1/2 PERLADO SIN ARO', 'STOPS', '14106', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S411A', 'STOP 2"1/2 PERLADO ARO ACERO', 'STOPS', '20576', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S412A', 'STOP 1" OJO DE BUEY ARO DUAL-VOLT x 5 UNIDADES', 'STOPS', '35265', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S412C', 'STOP 1" OJO DE BUEY CACHUCHA DUAL-VOLT x 5 UNIDADES', 'STOPS', '35265', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S413C', 'STOP 1" PEPINO CACHUCHA DUAL-VOLT x 5 UNIDADES', 'STOPS', '36765', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S414', 'STOP RECTANGULAR 24 LEDS SIN ARO DUAL VOLT', 'STOPS', '29975', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S414A', 'STOP RECTANGULAR 24 LEDS ARO ACERO DUAL VOLT', 'STOPS', '43172', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S420', 'STOP 2" NEON LUX SIN ARO', 'STOPS', '15871', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S420A', 'STOP 2" NEON LUX ARO ACERO', 'STOPS', '21753', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S421', 'STOP 2"1/2 NEON LUX SIN ARO', 'STOPS', '17645', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S421A', 'STOP 2"1/2 NEON LUX ARO ACERO', 'STOPS', '24104', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S422', 'STOP 1" 1/2 NEON LUX DUAL VOLT', 'STOPS', '14988', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S424', 'STOP RECTANGULAR NEON LUX SIN ARO DUAL VOLT', 'STOPS', '35266', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S424A', 'STOP RECTANGULAR NEON LUX ARO ACERO DUAL VOLT', 'STOPS', '48442', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S425A', 'STOP PEPINO 70MM DUAL-VOLT ARO', 'STOPS', '47892', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S425C', 'STOP PEPINO 70MM DUAL-VOLT CACHUCHA', 'STOPS', '35186', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S425P', 'STOP PEPINO 70MM DUAL-VOLT ARO CROMADO', 'STOPS', '35186', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S426P', 'STOP PEPINO 100MM DUAL-VOLT ARO', 'STOPS', '35186', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S426C', 'STOP PEPINO 100MM DUAL-VOLT CACHUCHA', 'STOPS', '35186', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S428', 'STOP TRIPLE PEQUEÑO NEON SENCILLO DUAL-VOLT', 'STOPS', '68767', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S429', 'STOP TRIPLE PEQUEÑO NEON CON REGLETA DUAL-VOLT', 'STOPS', '93453', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S430P', 'STOP PEPINO NEON LED 2" DUAL -VOLT ARO', 'STOPS', '22848', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S430C', 'STOP PEPINO NEON LED 2" DUAL -VOLT CACHUCHA', 'STOPS', '22848', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S431P', 'STOP PEPINO NEON LED 2" 1/2 DUAL -VOLT ARO', 'STOPS', '28179', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S431C', 'STOP PEPINO NEON LED 2" 1/2 DUAL -VOLT CACHUCHA', 'STOPS', '28179', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S432', 'STOP TRIANGULO NEON-LED DUAL -VOLT', 'STOPS', '43633', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S433', 'STOP 4" SECUENCIAL ESMERALDA SIN ARO DUAL-VOLT', 'STOPS', '51490', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S433A', 'STOP 4" SECUENCIAL ESMERALDA ARO ACERO DUAL-VOLT', 'STOPS', '61818', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S433P', 'STOP 4" SECUENCIAL ESMERALDA ARO PLASTICO DUAL-VOLT', 'STOPS', '55272', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S433SP', 'STOP 4" SECUENCIAL ESMERALDA ARO SOBREPONER DUAL-VOLT', 'STOPS', '55272', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('G100', 'PEPINO PISTOL STAR EN VIDRIO NEON-LED DUAL-VOLT ARO ACERO', 'STOPS', '110000', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R900A', 'REGLETA 9 LED FLUXS CON ARO PLASTICO x 4 UNIDADES', 'REGLETAS', '74056', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R901A', 'REGLETA 18 LEDS FLUXS CON ARO PLASTICO x 7 UNIDADES', 'REGLETAS', '234516', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R902', 'REGLETA 24 LEDS 4,8', 'REGLETAS', '45844', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R903A', 'REGLETA 15 LEDS FLUXS CON ARO PLASTICO x 6 UNIDADES', 'REGLETAS', '158696', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R906', 'REGLETA 44 CM NEON LUX', 'REGLETAS', '52898', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R907A', 'REGLETA 31 CM NEON LUX ARO PLASTICO x 7 UNIDADES', 'REGLETAS', '259198', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R908A', 'REGLETA 17 CM NEON LUX ARO PLASTICO x 4 UNIDADES', 'REGLETAS', '81111', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R909P', 'REGLETA 34CM NEON LUX PUNTAS CROMADAS PQ x 5 UNIDADES', 'REGLETAS', '211595', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R909', 'REGLETA 34CM NEON LUX PUNTAS CROMADAS', 'REGLETAS', '42319', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R910P', 'REGLETA 24CM NEON LUX PUNTAS CROMADAS PQ x 5 UNIDADES', 'REGLETAS', '154700', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R910', 'REGLETA 24CM NEON LUX PUNTAS CROMADAS', 'REGLETAS', '30940', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R911A', 'REGLETA 23CM NEON LUX CON ARO PLASTICO x 6 UNIDADES', 'REGLETAS', '174565', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R912A', 'REGLETA 5 LED FLUX CON ARO PLASTICO x 4 UNIDADES', 'REGLETAS', '59953', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R913A', 'REGLETA 10 CM NEON LUX CON ARO PLASTICO x 4 UNIDADES', 'REGLETAS', '63478', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R914P', 'REGLETA PEQUEÑA 24 LED PUNTAS CROMADAS PQ x 5 UNIDADES', 'REGLETAS', '163100', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R914', 'REGLETA PEQUEÑA 24 LED PUNTAS CROMADAS', 'REGLETAS', '32620', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R915P', 'REGLETA MEDIANA 36 LED PUNTAS CROMADAS PQ x 5 UNIDADES', 'REGLETAS', '229229', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R915', 'REGLETA MEDIANA 36 LED PUNTAS CROMADAS', 'REGLETAS', '45845', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R916', 'REGLETA ANCHA 35CM SECUENCIAL', 'REGLETAS', '83000', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('R917', 'REG ANCHA 44CM SECUENCIAL', 'REGLETAS', '116000', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('V20L', 'VELA EN LED X JGO DUAL VOLT', 'CAPOTERAS', '121647', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('LT400', 'LAMPARA CAPOTERA 13 LEDS', 'CAPOTERAS', '18514', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('LT500', 'LAMPARA CAPOTERA TIPO PEPINO DUAL-VOLT', 'CAPOTERAS', '60927', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('LT501', 'LAMPARA CAPOTERA TIPO PEPINO 2" 1/2 DUAL-VOLT', 'CAPOTERAS', '49353', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-017A', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO KENWORTH', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-015A', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO EAGLE', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-005A', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO WORKSTAR', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-006A', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO PROSTAR', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-INTA', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO DURASTAR CAREGATO', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-INT94', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO INTER 94 CAREMARRANO', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-014A', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO FREIGHTLINER COLUMBIA', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-014M2A', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO FREIGHTLINER M2', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-012CZ', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO CAREZAPATO', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-004A', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO INTER PODEROSA', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-007AA', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO KODIAK AERODINAMICO', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('MTM-007A', 'MATAMOSCO DESVIADOR EN ACRILICO Y ALUMINIO KODIAK', 'MATAMOSCOS', '435294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-017', 'ACRILICO MATAMOSCO KW', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-015', 'ACRILICO MATAMOSCO EAGLE', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-005', 'ACRILICO MATAMOSCO WORKSTAR', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-006', 'ACRILICO MATAMOSCO PROSTAR', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-INTA', 'ACRILICO MATAMOSCO DURASTAR CARE GATO', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-INT94', 'ACRILICO MATAMOSCO 4700 CAREMARRANO', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-014', 'ACRILICO MATAMOSCO FREIGTHLINER COLUMBIA', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-014M2', 'ACRILICO MATAMOSCO FREIGTHLINER M2', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-012', 'ACRILICO MATAMOSCO CARE ZAPATO', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-004', 'ACRILICO MATAMOSCO INTER PODEROSA', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-007', 'ACRILICO MATAMOSCO KODIAK', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('AC-007A', 'ACRILICO MATAMOSCO KODIAK AERODINAMICO', 'ACRILICOS', '194115', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('BS-2A', 'BASE SEMAFORO 2 TORNILLOS ALUMINIO BRILLADA X JGO', 'ACCESORIOS', '21176', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('BS-4A', 'BASE SEMAFORO 4 TORNILLOS ALUMINIO BRILLADA X JGO', 'ACCESORIOS', '35294', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('C302P', 'CACHUCHA SEMAFORO CUADRADO 4" PLASTICO CROMADO X2', 'ACCESORIOS', '17633', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('C315P', 'CACHUCHA SEMAFORO CUADRADO 3" PLASTICO CROMADO X2', 'ACCESORIOS', '13000', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CS425', 'CACHUCHA PEPINO BAJO PLASTICO CROMADO', 'ACCESORIOS', '8396', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CS426', 'CACHUCHA PEPINO ALTO PLASTICO CROMADO', 'ACCESORIOS', '8396', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CS430', 'CACHUCHA PEPINO 2" PLASTICO CROMADO', 'ACCESORIOS', '7220', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CS431', 'CACHUCHA CACHUCHA PEPINO 2" 1/2 PLASTICO CROMADO', 'ACCESORIOS', '7220', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('E900', 'ESPEJO BUSCARATA CARCASA CROMADA', 'ACCESORIOS', '50116', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3013PC', 'BOTON TAPAGOLOSO PUNTA PLANA PAQUETE x 10 UNIDADES', 'ACCESORIOS', '13539', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3012PC', 'BOTON TAPAGOLOSO PUNTA DIAMANTE PAQUETE x 10 UNIDADES', 'ACCESORIOS', '13539', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3014PC', 'BOTON TAPAGOLOSO HEXAGONAL PAQUETE x 40 UNIDADES', 'ACCESORIOS', '52941', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3003PC', 'BOTON COJINERIA KENWORTH PAQUETE x 10 UNIDADES', 'ACCESORIOS', '17252', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3002PC', 'BOTON TAPA PERSIANA PAQUETE x 10 UNIDADES', 'ACCESORIOS', '13539', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3007PC', 'BOTON COJINERIA EAGLE PAQUETE x 10 UNIDADES', 'ACCESORIOS', '17252', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3004PC', 'BOTON TAPA PERSIANA HEXAGONAL PAQUETE x 20 UNIDADES', 'ACCESORIOS', '35294', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2012P', 'TAPA TUERCA RIN DISCO 3MM ESFERA-PRESION PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '41435', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2012P-C', 'TAPA TUERCA RIN DISCO 3MM ESFERA-PRESION CAJA X 50 UNIDADES', 'TAPATUERCAS', '207175', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2012R', 'TAPA TUERCA RIN DISCO 33MM ESFERA-ROSCA PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '43624', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2012R-C', 'TAPA TUERCA RIN DISCO 33MM ESFERA-ROSCA CAJA X 50 UNIDADES', 'TAPATUERCAS', '218120', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2013P', 'TAPA TUERCA RIN DISCO 33MM PUNTA BALA-PRESION PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '41435', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2013P-C', 'TAPA TUERCA RIN DISCO 33MM PUNTA BALA-PRESION CAJA X 50 UNIDADES', 'TAPATUERCAS', '207175', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2013R', 'TAPA TUERCA RIN DISCO 33MM PUNTA BALA-ROSCA PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '43624', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2013R-C', 'TAPA TUERCA RIN DISCO 33MM PUNTA BALA-ROSCA CAJA X 50 UNIDADES', 'TAPATUERCAS', '218120', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2014P', 'TAPA TUERCA RIN DISCO 33MM MANIJA PRESION PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '41435', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2014P-C', 'TAPA TUERCA RIN DISCO 33MM MANIJA PRESION CAJA X 60 UNIDADES', 'TAPATUERCAS', '248612', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2014R', 'TAPA TUERCA RIN DISCO 33MM MANIJA ROSCA PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '43624', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2014R-C', 'TAPA TUERCA RIN DISCO 33MM MANIJA ROSCA CAJA X 60 UNIDADES', 'TAPATUERCAS', '261741', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2008PL', 'TAPA TUERCA NPR 41MM PLANA LISA-PRESION PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '34894', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2008PL-C', 'TAPA TUERCA NPR 41MM PLANA LISA-PRESION CAJA X 60 UNIDADES', 'TAPATUERCAS', '209364', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2008PP', 'TAPA TUERCA NPR 41MM PLANA PRISMA-PRESION PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '34894', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2008PP-C', 'TAPA TUERCA NPR 41MM PLANA PRISMA-PRESION CAJA X 60 UNIDADES', 'TAPATUERCAS', '209364', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2008PCH', 'TAPA TUERCA NPR 41MM PLANA LOGO CHEVROLET-PRESION PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '34894', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2008PCH-C', 'TAPA TUERCA NPR 41MM PLANA LOGO CHEVROLET-PRESION CAJA X 60 UNIDADES', 'TAPATUERCAS', '209364', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2008PH', 'TAPA TUERCA NPR 41MM PLANA LOGO HINO-PRESION PAQUETE X 10 UNIDADES', 'TAPATUERCAS', '34894', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('2008PH-C', 'TAPA TUERCA NPR 41MM PLANA LOGO HINO-PRESION CAJA X 60 UNIDADES', 'TAPATUERCAS', '209364', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3015P', 'TAPA TUERCA 3"1/2 HEXAGONAL 33MM PRESION PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '23988', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3015P-C', 'TAPA TUERCA 3"1/2 HEXAGONAL 33MM PRESION CAJA X 50 UNIDADES', 'TAPATUERCAS', '239882', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3015R', 'TAPA TUERCA 3"1/2 HEXAGONAL 33MM ROSCA PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '26171', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3015R-C', 'TAPA TUERCA 3"1/2 HEXAGONAL 33MM ROSCA CAJA X 50 UNIDADES', 'TAPATUERCAS', '261706', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3016P', 'TAPA TUERCA 5" HEXAGONAL 33MM PRESION PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '53312', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3016P-C', 'TAPA TUERCA 5" HEXAGONAL 33MM PRESION CAJA X 50 UNIDADES', 'TAPATUERCAS', '533120', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3016R', 'TAPA TUERCA 5" HEXAGONAL 33MM ROSCA PAQUETE x 5 UNIDADES', 'TAPATUERCAS', '55388', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3016R-C', 'TAPA TUERCA 5" HEXAGONAL 33MM ROSCA CAJA x 50 UNIDADES', 'TAPATUERCAS', '533120', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3017P', 'TAPA TUERCA 3"1/2 HEXAGONAL 41MM PRESION PAQUETE 5 UNIDADES', 'TAPATUERCAS', '23988', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3017P-C', 'TAPA TUERCA 3"1/2 HEXAGONAL 41MM PRESION CAJA X 50 UNIDADES', 'TAPATUERCAS', '239880', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3018P', 'TAPA TUERCA 5" HEXAGONAL 41MM PRESION PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '53312', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3018P-C', 'TAPA TUERCA 5" HEXAGONAL 41MM PRESION CAJA X 50 UNIDADES', 'TAPATUERCAS', '533120', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3019P', 'TAPA TUERCA 3" 1/2 CILINDRICA 33MM PRESION PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '23988', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3019P-C', 'TAPA TUERCA 3" 1/2 CILINDRICA 33MM PRESION CAJA X 50 UNIDADES', 'TAPATUERCAS', '239880', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3019R', 'TAPA TUERCA 3" 1/2 CILINDRICA 33MM ROSCA PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '26171', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3019R-C', 'TAPA TUERCA 3" 1/2 CILINDRICA 33MM ROSCA CAJA X 50 UNIDADES', 'TAPATUERCAS', '261171', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3020R', 'TAPA TUERCA 5" CILINDRICA 33MM ROSCA PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '55388', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3020R-C', 'TAPA TUERCA 5" CILINDRICA 33MM ROSCA CAJAX 50 UNIDADES', 'TAPATUERCAS', '553880', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3020P', 'TAPA TUERCA 5" CILINDRICA 33MM PRESION PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '53312', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3020P-C', 'TAPA TUERCA 5" CILINDRICA 33MM PRESION CAJA X 50 UNIDADES', 'TAPATUERCAS', '533120', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3021-C', 'TAPA CHASIS HEXAGONAL 24MM EXTRA LARGO KW CAJA X 120 UNIDADES', 'TAPATUERCAS', '470539', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3022P', 'TAPATUERCA CRUCETA 33MM PRESION PAQUETE X 5', 'TAPATUERCAS', '37646', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3022R', 'TAPATUERCA CRUCETA 33MM ROSCA PAQUETE X 5', 'TAPATUERCAS', '38822', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3023P', 'TAPA TUERCA PUNTA MANIJA 33MM PRESION PAQUETE X 5', 'TAPATUERCAS', '37646', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3023R', 'TAPA TUERCA PUNTA MANIJA 33MM ROSCA PAQUETE X 5', 'TAPATUERCAS', '38822', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3024P', 'TAPA TUERCA MANIJA ALTA 33 MM PRESION PAQUETE X 5', 'TAPATUERCAS', '37646', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3024R', 'TAPA TUERCA MANIJA ALTA 33 MM ROSCA PAQUETE X 5', 'TAPATUERCAS', '38822', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3025P', 'TAPA TUERCA PRESION RANURADA TRAGALUZ AMARILLO PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '37646', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3025R', 'TAPA TUERCA ROSCA RANURADA TRAGALUZ AMARILLO PAQUETE X 5 UNIDADES', 'TAPATUERCAS', '38822', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3026P', 'TAPA TUERCA CORONA PRESION 33MM PAQUETE X 5', 'TAPATUERCAS', '37646', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3026R', 'TAPATUERCA CORONA ROSCA 33MM PAQUETE X 5', 'TAPATUERCAS', '38822', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('5001R', 'TAPA RIN CILINDRICO CON CAJA SIN TAPATUERCAS', 'TAPA RIN', '69634', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('5002R', 'TAPA RIN ESFERA CON CAJA SIN TAPA TUERCAS', 'TAPA RIN', '71249', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('5003R', 'TAPA RIN HEXAGONAL CON CAJA SIN TAPATUERCAS', 'TAPA RIN', '71249', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('5001E', 'TAPA EJE CILINDRO CON CAJA SIN TAPA TUERCAS', 'TAPA EJES', '87209', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('5002E', 'TAPA EJE ESFERA CON CAJA SIN TAPATUERCAS', 'TAPA EJES', '88349', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('5003E', 'TAPA EJE HEXAGONAL CON CAJA SIN TAPATUERCAS', 'TAPA EJES', '88349', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('B-L570', 'BASE LICUADORA POLICARBONATO', 'REPUESTOS', '35294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('VIC57', 'VASO INTERNO POLICARBONATO', 'REPUESTOS', '35294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('VEC57', 'VASO EXTERNO POLICARBONATO', 'REPUESTOS', '35294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CIE-L570', 'CIRCUITO ENSAMBLADO L570', 'REPUESTOS', '115294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CIE-L570BI', 'CIRCUITO ENSAMBLADO L570 BLUE ICE', 'REPUESTOS', '116706', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CIE-L580M', 'CIRCUITO DE CONTROL ENSAMBLADO MATRIZ L580', 'REPUESTOS', '164706', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CE-L580', 'CAJON ENSAMBLADO LICUADORA L580 CON TAPA SUPERIOR', 'REPUESTOS', '164706', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CI001FV', 'BALASTRO SENCILLO CAJA INTERMITENTE DUAL VOLTX PQ 5 UNIDADES', 'REPUESTOS', '94118', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CI002FV', 'BALASTRO DOBLE CAJA INTERMITENTE DUAL VOLT X PQ 5 UNIDADES', 'REPUESTOS', '123529', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('ARO-L108P', 'ARO PLASTICO OVALADO L108-L109-L111', 'REPUESTOS', '4706', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('ARO-L108', 'ARO ACERO OVALADO L108-L109-L111', 'REPUESTOS', '13994', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('ARO-L108SP', 'ARO SOBREPONER OVALADO L108-L109-L111', 'REPUESTOS', '4846', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('ARO-S404P', 'ARO PLASTICO STOP 4" S404-S405', 'REPUESTOS', '4846', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('ARO-S404', 'ARO ACERO INOX 4" HUECO LISO', 'REPUESTOS', '11448', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('ARO-S404SP', 'ARO PLASTICO STOP 4" SOBREPONER S404-S405', 'REPUESTOS', '4706', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('RAE-S302', 'REPUESTO ARO SEMAFORO CUADRADO S302-S306', 'REPUESTOS', '39294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('CIE-AUXS302', 'AUXILIAR ENSAMBLADO SEMAFORO DUAL VOLT S302-S306', 'REPUESTOS', '15882', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('BO-R902', 'BOCEL ABS REGLETA 24 LED X 4 UNIDADES', 'REPUESTOS', '59953', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('LBR', 'LUNA ESPEJO BUSCARATA CON EMPAQUE', 'REPUESTOS', '25882', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S306R', 'CARITA SEMAFORO CUADRADO NEON LUX', 'REPUESTOS', '40654', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S302R', 'CARITA SEMAFORO CUADRADO PERLADO', 'REPUESTOS', '37518', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S315R', 'CARITA SEMAFORO 3" PERLADO', 'REPUESTOS', '20588', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('S326R', 'CARITA SEMAFORO 3" NEON LUX', 'REPUESTOS', '22941', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('BLO-001', 'BASE LICUADORA OMEGA', 'REPUESTOS', '35294', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('BLBA-001', 'BASE LICUADORA BOTA AGUA', 'REPUESTOS', '41960', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('PLT-L115O', 'SOPORTE LAMPARA LATERAL CON OJO DE BUEY L115-L112', 'REPUESTOS', '17353', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('PLT-L115', 'SOPORTE LAMPARA LATERAL L115-L112', 'REPUESTOS', '12768', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('PLT-S425O', 'SOPORTE PEPINO STOP CON OJO DE BUEY', 'REPUESTOS', '23136', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('PLT-96', 'SOPORTE DE LATERAL OVALADO SENCILLO', 'REPUESTOS', '13725', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('PLT-9495', 'SOPORTE GRANDRE TRUCK STEEL ALTO RELIEVE', 'REPUESTOS', '6971', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('PLT-9198', 'SOPORTE GRANDRE TRUCK STEEL ALTO RELIEVE', 'REPUESTOS', '7842', 'Unidad');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('3TPD16', 'TORNILLO PUNTA DIAMANTE 3/16 PAQUETE X 10 (PRECIO FINAL SIN IVA)', 'REPUESTOS', '13659', 'Paquete');
INSERT INTO `productos` (`nombre`, `descripcion`, `categoria`, `precio_base`, `unidad_medida`) VALUES ('1TPD14', 'TORNILLO PUNTA DIAMANTE 1/4 PAQUETE X 10 (PRECIO FINAL SIN IVA)', 'REPUESTOS', '20718', 'Paquete');